### ISSUE TITLE
Error using step4a.js

### ISSUE THREAD

**Issue by gstaniland** [ed-gonzalez/Cognos-Custom-Control-Tutorial#1]
Hi Ed
I'm trying to use your code in C11.0.6.  I have some success, but get this message popping up:
(screenshot attached).
The only changes I made is adding a Mapbox key, and changing the center to land on South Africa.
The map displays ok, with all the points correctly plotted, but the navigation of the map doesn't work properly.  And no navigation tools are displayed.  When the report first runs, it runs for aaaagggess, and then I hit cancel.
Filtering work well.
Any ideas?
thanks so much
Gill.
![js message](https://user-images.githubusercontent.com/28891173/31897253-1c63a992-b816-11e7-8ab1-724872c2774a.JPG)
![saweatherstations](https://user-images.githubusercontent.com/28891173/31897254-1d053a82-b816-11e7-8e91-c637b4033ea1.JPG)

**Comment by ed-gonzalez** [comment]
Hi

I'm not sure about the time it takes to load.  But a couple of things to
try with the controls.

1.  In the properties for the custom control try changing the "With Event
Propagation" to true .
2. Make sure you are getting the MapBox CSS. file it is the one that
manages the placement of the controls and the MapBox watermark at the
bottom of the map.
It should be loaded in the init section as such:

*$("head link[rel='stylesheet']").last().after("<link
href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.34.0/mapbox-gl.css
<https://api.tiles.mapbox.com/mapbox-gl-js/v0.34.0/mapbox-gl.css>'
rel='stylesheet' />");*

*Give that a try and let me know what happens.  You can contact me directly
at edgonzalez@icdata.io <edgonzalez@icdata.io>*

*Good Luck*

*Ed*



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by gstaniland** [comment]
Hi Ed

I've got it working! :)
After a bit of digging around, I found a problem in my data source! A LngLat that was null.
Easy when you know how :)
